### ISSUE TITLE
Github Desktop

### ISSUE THREAD

**Issue by MaximNelishew** [AsahiOcean/AsahiOcean#1]
Привет
Подскажи, пожалуйста, как решить этот трабл в Github Desktop
**Cannot push these commits as they contain an email address marked as private on GitHub.**

**Comment by AsahiOcean** [comment]
Зайди сюда [https://github.com/settings/emails](https://github.com/settings/emails)
и сними галочку с "**Block command line pushes that expose my email**"

<img width="804" alt="Block command line pushes that expose my email" src="https://user-images.githubusercontent.com/61920574/100361227-b5f64d00-301b-11eb-8387-3eec6656c8d2.png">

p.s. не забудь добавить приватный email в гит через:
**git config user.email "...@users.noreply.github.com"**
